import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
} from "react-icons/ai";

import Image from "next/image";

import web3logo from "../public/web3/web3logo.jpg";

import { useRouter } from "next/router";
const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className="">
      <Head>
        <title>Doungchan Sroeun | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="profile.jpg" />
      </Head>
      <main className="md:px-20 lg:px-40">
        <section className="min-h-screen mx-4">
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              DoungChan Sroeun
            </h2>
            <h3 className="text-2xl py-2 text-white md:text-3xl">
              Software Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-500 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let is get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <a>
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/doungchan-sroeun-9524a8253/">
                <AiFillLinkedin />
              </a>

              <a href="https://www.facebook.com/doung.chan.3950/">
                <AiFillFacebook />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                src={"/profile.jpg"}
                alt={"profile"}
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </section>
        <section className="px-10">
          <div>
            <h3 className="text-start text-3xl py-1 text-teal-600">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-500 ">
              A qualified software engineer with 3 years and a half of
              experience with excellent front-end and mobile app development and
              designing skills, as well as a flexible working environment,
              Responsibility, and willingness to learn new things.
            </p>
            <p className="text-md py-2 leading-8 text-gray-500 ">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <h1 className="text-3xl py-1 1 text-teal-600">Skill</h1>
          <div className="lg:flex gap-10 bg-gray-800 justify-center items-center p-4 rounded-lg">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white flex-1">
              {/* <Image src={design} width={100} height={100} /> */}

              <h3 className="text-lg font-medium    ">Design</h3>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white flex-1">
              {/* <Image src={code} width={100} height={100} /> */}
              <h3 className="text-lg font-medium  pb-2 ">Front End</h3>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">React js</p>
              <p className="text-gray-800 py-1">Next js</p>
              <p className="text-gray-800 py-1">Vue js</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white flex-1">
              {/* <Image src={consulting} width={100} height={100} /> */}
              <h3 className="text-lg font-medium pb-2 ">Back End</h3>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Node js</p>
              <p className="text-gray-800 py-1">Spring Boot</p>
              <p className="text-gray-800 py-1">Golang</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white flex-1">
              {/* <Image src={consulting} width={100} height={100} /> */}
              <h3 className="text-lg font-medium  pb-2 ">Mobile App</h3>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Flutter</p>
              <p className="text-gray-800 py-1">React Native</p>
              <p className="text-gray-800 py-1">Java</p>
            </div>
          </div>
        </section>
        <section className="px-10">
          <div>
            <h3 className="text-3xl py-1 1 text-teal-600 justify-center items-center">
              Project
            </h3>
            <p className="text-md py-2 leading-8 text-gray-500">
              Since the beginning of my journey as a designer and developer, I
              have done alot of work for
              <span className="text-teal-500"> KIT </span> as a internship and
              collaborated with talanted people to create digital products for
              both business and consumer use.
            </p>
          </div>
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  relative overflow-hidden rounded-md cursor-pointer">
            <div
              className="relative group basis-1/3 flex-1 overflow-hidden rounded-md cursor-pointer"
              onClick={() => {
                router.push("/project/web3");
              }}
            >
              <Image
                className="absolute rounded-md object-cover ease-in-out duration-500 group-hover:rotate-6 group-hover:scale-125"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3logo}
                alt={"Connection"}
              />
              <div className="absolute bottom-0 justify-center items-center text-white p-4 text-2xl bg-slate-500 bg-opacity-30 w-full">
                <h2 className="text-xl py-2 text-teal-500 font-medium  md:text-3xl">
                  Web 3.0
                </h2>
              </div>
            </div>
            <div
              className="relative group basis-1/3 flex-1 overflow-hidden rounded-md cursor-pointer"
              onClick={() => {
                router.push("/project/sms");
              }}
            >
              <Image
                className="absolute rounded-md object-cover ease-in-out duration-500 group-hover:rotate-6 group-hover:scale-125"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/sms/smshome.png"}
                alt={"Connection"}
              />
              <div className="absolute bottom-0 justify-center items-center text-white p-4 text-2xl bg-slate-500 bg-opacity-30 w-full">
                <h2 className="text-md py-2 text-teal-500 font-medium  md:text-3xl">
                  School Management System
                </h2>
              </div>
            </div>
            <div
              className="relative group basis-1/3 flex-1 overflow-hidden rounded-md cursor-pointer"
              onClick={() => {
                router.push("/project/vconnect");
              }}
            >
              <Image
                className="absolute rounded-md object-cover ease-in-out duration-500 group-hover:rotate-6 group-hover:scale-125"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={"/flutter.jpg"}
                alt={"Connection"}
              />
              <div className="absolute bottom-0 justify-center items-center text-white p-4 text-2xl bg-slate-500 bg-opacity-30 w-full">
                <h2 className="text-md py-2 text-teal-500 font-medium  md:text-3xl">
                  Vconnect
                </h2>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
