import React from "react";
import { Carousel } from "react-responsive-carousel";

import "react-responsive-carousel/lib/styles/carousel.min.css";

import Image from "next/image";
import SwiperComponent from "../../components/slider/SwiperComponent";
import Head from "next/head";
const efind: React.FC = () => {
  const data = [
    "/efind/category.png",
    "/efind/home page.png",
    "/efind/profile screen.png",
    "/efind/shop detail.png",
    "/efind/sign up screen.png",
  ];

  return (
    <>
      <Head>
        <title>Doungchan Sroeun | Vconnect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>
      <div className="flex flex-col m-8">
        <section className="flex flex-col w-full">
          <div className="flex flex-col md:flex-row lg:flex-row gap-5 justify-center items-center gap-x-16">
            <div className="flex flex-col justify-center items-center rounded-lg  w-[200px] h-[400px]">
              <Carousel
                autoPlay={true}
                infiniteLoop={true}
                stopOnHover={false}
                showThumbs={false}
              >
                {data.map((item: string, index: number) => (
                  <div
                    key={index}
                    className="justify-center items-center rounded-md overflow-hidden"
                  >
                    <Image
                      src={item}
                      alt={`image ${index + 1}`}
                      className="w-60 h-60 object-cover rounded-3xl "
                      width={420}
                      height={850}
                    />
                  </div>
                ))}
              </Carousel>
            </div>
            <div className="flex flex-col justify-center items-center w-full lg:w-1/2">
              <h1 className="text-xl dark:text-teal-400 font-bold">eFind</h1>
              <line className="w-full h-1 bg-gray-500 my-4" />
              <p className="text-gray-500 text-sm">
                The purpose of this app is to help people more easier in finding
                the shop or service that they want. This app is developed with
                Flutter and Node JS.
              </p>
            </div>
          </div>
        </section>
        <line className="w-full h-1 bg-gray-500 my-4" />
        <h1 className="text-xl dark:text-teal-400 font-bold">
          Technology Used
        </h1>

        <section className="w-full mt-10">
          <button className="bg-gray-500 text-white px-4 py-2 rounded-md mt-4 mr-4">
            Flutter
          </button>
          <button className="bg-gray-500 text-white px-4 py-2 rounded-md mt-4">
            Node JS
          </button>
        </section>
      </div>
    </>
  );
};

export default efind;
