import React from "react";
import { Carousel } from "@material-tailwind/react";
import Slider from "../../components/slider/Slider";
import SwiperComponent from "../../components/slider/SwiperComponent";
import Head from "next/head";
import Image from "next/image";

interface SlideImage {
  url: string;
}

// const slide_img: SlideImage[] = [
//   {
//     url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7YP5oD8dvFDxFPdfdDYfAmHo1pRu61_f6GvEaMl5U&s",
//   },
//   {
//     url: "https://www.vectorlogo.zone/logos/supabase/supabase-ar21.svg",
//   },
// ];
const ogp: React.FC = () => {
  const data = [
    "/ogp/Dashboard month.png",
    "/ogp/Product_list.png",
    "/ogp/QR history.png",
    "/ogp/Store_list_dangkao.png",
  ];

  return (
    <>
      <Head>
        <title>Doungchan Sroeun | OGP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>
      <div className="flex flex-col m-8">
        <h1 className="text-3xl dark:text-teal-400 font-bold">Project</h1>
        <section className="flex flex-col w-full my-10 md:my-4">
          <div className="flex flex-col md:flex-row lg:flex-row gap-5">
            <div className="flex flex-col justify-center items-center md:w-full rounded-lg lg:w-1/2 overflow-hidden">
              <Slider data={data} />
            </div>
            <div className="flex flex-col justify-center items-center w-full lg:w-1/2">
              <h1 className="text-xl dark:text-teal-400 font-bold">OGP</h1>
              <line className="w-full h-1 bg-gray-500 my-4" />
              <p className="text-gray-500 text-sm">
                OGP is the dashboard for the owner of the store to manage their
                store and product. The owner can add, edit, delete the product
                and store. The owner can also see the history of the QR code
                that the customer scan.
              </p>
            </div>
          </div>
        </section>
        <line className="w-full h-1 bg-gray-500 my-4" />
        <h1 className="text-xl dark:text-teal-400 font-bold">
          Technology Used
        </h1>

        <section className="w-full mt-4">
          {/* <div>
            {slide_img.map((item: SlideImage, index: number) => (
              <div
                key={index}
                className="justify-center items-center rounded-md overflow-hidden"
              >
                <Image
                  src={item.url}
                  alt={`image ${index + 1}`}
                  className="w-60 h-60 object-cover rounded-3xl"
                  width={420}
                  height={850}
                />
              </div>
            ))}
          </div> */}
          <button className="bg-gray-500 text-white px-4 py-2 rounded-md mt-4 mr-4">
            Refind JS
          </button>
          <button className="bg-gray-500 text-white px-4 py-2 rounded-md mt-4">
            Supabase
          </button>
        </section>
      </div>
    </>
  );
};

export default ogp;
