import React from "react";
import { Carousel } from "@material-tailwind/react";
import Slider from "../../components/slider/Slider";
import SwiperComponent from "../../components/slider/SwiperComponent";
import Head from "next/head";
const PromoKh = () => {
  const data = [
    "/promokh/Food category.png",
    "/promokh/Create new promotion page.png",
    "/promokh/Create new promotion page.png",
    "/promokh/Create new promotion page.png",
    "/promokh/User profile.png",
    "/promokh/404 page.png",
  ];
  const slide_img = [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/591px-Nextjs-logo.svg.png?20230404233503",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/900px-Tailwind_CSS_Logo.svg.png?20211001194333",
    "https://img.icons8.com/?size=512&id=90519&format=png ",
    "https://w7.pngwing.com/pngs/956/695/png-transparent-mongodb-original-wordmark-logo-icon-thumbnail.png",
    "https://w7.pngwing.com/pngs/256/416/png-transparent-docker-github-node-js-mongodb-computer-software-github-blue-marine-mammal-logo-thumbnail.png",
  ];
  return (
    <>
      <Head>
        <title>Doungchan Sroeun | PromoKh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>
      <div className="flex flex-col m-8">
        <h1 className="text-3xl text-teal-400 font-bold md:mb-4">Project</h1>
        <section className="flex flex-col w-full">
          <div className="flex flex-col md:flex-row lg:flex-row md:gap-5 my-10 md:my-3">
            <div className="flex flex-col justify-center md:w-full rounded-lg lg:w-1/2">
              <Slider data={data} />
            </div>
            <div className="flex flex-col justify-center items-center w-full lg:w-1/2">
              <h1 className="text-xl dark:text-teal-400 font-bold">PromoKh</h1>
              <line className="w-full h-1 bg-gray-500 my-4" />
              <p className="text-gray-500 text-sm">
                PromoKh is a web application that allows users to create
                promotions for their products and services. The application
                allows users to create promotions for their products and
                services. The application allows users to create promotions for
                their products and services. The application allows users to
                create promotions for their products and services.
              </p>
            </div>
          </div>
        </section>
        <line className="w-full h-1 bg-gray-500 my-4" />
        <h1 className="text-xl dark:text-teal-400 font-bold">
          Technology Used
        </h1>

        <section className="w-full mt-10">
          <div className="flex justify-center items-center h-full">
            <SwiperComponent slide_img={slide_img} slidesPerView={4} />
          </div>
        </section>
      </div>
    </>
  );
};

export default PromoKh;
