import React from "react";
import { Carousel } from "@material-tailwind/react";
import Slider from "../../components/slider/Slider";
import SwiperComponent from "../../components/slider/SwiperComponent";
import Head from "next/head";
const SchoolManagementSystem = () => {
  const data = [
    "/sms/smshome.png",
    "/sms/sms_attendance.png",
    "/sms/sms_report.png",
    "/sms/sms_class.png",
    "/sms/sms_schedule.png",
  ];
  const slide_img = [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Vitejs-logo.svg/615px-Vitejs-logo.svg.png?20220412224743",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/768px-Typescript_logo_2020.svg.png?20221110153201",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Electron_Software_Framework_Logo.svg/640px-Electron_Software_Framework_Logo.svg.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/900px-Tailwind_CSS_Logo.svg.png?20211001194333",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/885px-Node.js_logo.svg.png?20170401104355",
    "https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png?20170812110931",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/810px-Postgresql_elephant.svg.png?20080116191800",
    "https://upload.wikimedia.org/wikipedia/commons/6/64/Expressjs.png?20170429090805",
  ];
  return (
    <>
      <Head>
        <title>Doungchan Sroeun | SchoolManagementSystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>
      <div className="flex flex-col m-8">
        <h1 className="text-3xl text-teal-400 font-bold md:mb-4">Project</h1>
        <section className="flex flex-col w-full">
          <div className="flex flex-col md:flex-row lg:flex-row md:gap-5 my-10 md:my-3">
            <div className="flex flex-col justify-center md:w-full rounded-lg lg:w-1/2">
              <Slider data={data} />
            </div>
            <div className="flex flex-col justify-center items-center w-full lg:w-1/2">
              <h1 className="text-xl dark:text-teal-400 font-bold">
                School management system
              </h1>
              <line className="w-full h-1 bg-gray-500 my-4" />
              <p className="text-gray-500 text-sm">
                School management system is a web application that helps school
                to manage their student, teacher, class, schedule, attendance,
                and report. This application is built with React, Typescript,
                Vite, Tailwindcss, Electron, Nodejs, Express, Postgresql, and
                Swagger.
              </p>
            </div>
          </div>
        </section>
        <line className="w-full h-1 bg-gray-500 my-4" />
        <h1 className="text-xl dark:text-teal-400 font-bold">
          Technology Used
        </h1>

        <section className="w-full mt-10">
          <div className="flex justify-center items-center h-full">
            <SwiperComponent slide_img={slide_img} slidesPerView={4} />
          </div>
        </section>
      </div>
    </>
  );
};

export default SchoolManagementSystem;
